package br.com.luizotavionazar.authluiz.domain.auditoria.enums;

public enum AcaoAuditoria {

    // SEGURANCA
    LOGIN_SUCESSO,
    LOGOUT,
    LOGIN_FALHA,
    CADASTRO,
    RECUPERACAO_SENHA_INICIADA,
    RECUPERACAO_SENHA_CODIGO_VALIDADO,
    RECUPERACAO_SENHA_REDEFINIDA,
    EMAIL_CONFIRMADO,
    ALTERAR_SENHA,
    CONTA_DELETADA,
    LOGIN_GOOGLE,
    LOGIN_GOOGLE_FALHA,
    SETUP_CONFIGURADO,

    // ATIVIDADE
    ALTERAR_NOME,
    ALTERAR_EMAIL_SOLICITADO,
    ALTERAR_TELEFONE,
    TELEFONE_CONFIRMADO,
    VINCULAR_GOOGLE,
    DESVINCULAR_GOOGLE,
    VERIFICACAO_LOGIN_SUCESSO,
    VERIFICACAO_LOGIN_FALHA,
    ATIVAR_2FA,
    DESATIVAR_2FA,
    ATIVAR_VERIFICACAO_EXTRA,
    DESATIVAR_VERIFICACAO_EXTRA,
    BACKUP_CODES_REGENERADOS,
    IP_CONFIAVEL_ADICIONADO,
    IP_CONFIAVEL_REMOVIDO
}
